CREATE TABLE IF NOT EXISTS registrations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,  
  secondmail VARCHAR(150) UNIQUE,
  phone VARCHAR(15) NOT NULL,
  college VARCHAR(150) NOT NULL,
  student_year INTEGER NOT NULL,
  amount INTEGER,
  food VARCHAR(50) NOT NULL,
  utr BIGINT UNIQUE NOT NULL,
  screenshot_hash TEXT UNIQUE NOT NULL
);

ALTER TABLE registrations
ADD COLUMN blacklist BOOLEAN DEFAULT FALSE;
