CREATE TABLE IF NOT EXISTS register (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  phone VARCHAR(15) NOT NULL,
  college VARCHAR(150) NOT NULL,
  student_year INTEGER NOT NULL,
  food VARCHAR(50) NOT NULL
);
